// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/notification_service.proto

// Protobuf Java Version: 3.25.1
package notification;

public final class NotificationServiceOuterClass {
  private NotificationServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notification_UpdateMailingRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_notification_UpdateMailingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notification_UpdateGroupRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_notification_UpdateGroupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notification_UpdateNotifyRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_notification_UpdateNotifyRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\036api/notification_service.proto\022\014notifi" +
      "cation\032\014common.proto\032\033google/protobuf/em" +
      "pty.proto\"0\n\024UpdateMailingRequest\022\n\n\002id\030" +
      "\001 \001(\003\022\014\n\004time\030\002 \001(\005\"/\n\022UpdateGroupReques" +
      "t\022\n\n\002id\030\001 \001(\003\022\r\n\005group\030\002 \001(\t\"0\n\023UpdateNo" +
      "tifyRequest\022\n\n\002id\030\001 \001(\003\022\r\n\005value\030\002 \001(\0102\243" +
      "\003\n\023NotificationService\022K\n\rUpdateMailing\022" +
      "\".notification.UpdateMailingRequest\032\026.go" +
      "ogle.protobuf.Empty\0228\n\nGetMailing\022\021.comm" +
      "on.IdRequest\032\027.common.BooleanResponse\022G\n" +
      "\013UpdateGroup\022 .notification.UpdateGroupR" +
      "equest\032\026.google.protobuf.Empty\0228\n\nCheckG" +
      "roup\022\021.common.IdRequest\032\027.common.Boolean" +
      "Response\022I\n\014UpdateNotify\022!.notification." +
      "UpdateNotifyRequest\032\026.google.protobuf.Em" +
      "pty\0227\n\tGetNotify\022\021.common.IdRequest\032\027.co" +
      "mmon.BooleanResponseB\036\n\032no" +
      "tificationP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          common.Common.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_notification_UpdateMailingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_notification_UpdateMailingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_notification_UpdateMailingRequest_descriptor,
        new String[] { "Id", "Time", });
    internal_static_notification_UpdateGroupRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_notification_UpdateGroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_notification_UpdateGroupRequest_descriptor,
        new String[] { "Id", "Group", });
    internal_static_notification_UpdateNotifyRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_notification_UpdateNotifyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_notification_UpdateNotifyRequest_descriptor,
        new String[] { "Id", "Value", });
    common.Common.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
