/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import jooq.Keys;
import jooq.Public;
import jooq.tables.records.LessonsRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Lessons extends TableImpl<LessonsRecord> {

    private static final long serialVersionUID = 1L;

    public static final Lessons LESSONS = new Lessons();

    @Override
    public Class<LessonsRecord> getRecordType() {
        return LessonsRecord.class;
    }

    public final TableField<LessonsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    public final TableField<LessonsRecord, Integer> GROUPID = createField(DSL.name("groupid"), SQLDataType.INTEGER, this, "");

    public final TableField<LessonsRecord, String> DISCIPLINE = createField(DSL.name("discipline"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    public final TableField<LessonsRecord, LocalDate> CLASSDATE = createField(DSL.name("classdate"), SQLDataType.LOCALDATE.nullable(false), this, "");

    public final TableField<LessonsRecord, String> CLASSTIME = createField(DSL.name("classtime"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    public final TableField<LessonsRecord, String> CLASSROOM = createField(DSL.name("classroom"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private Lessons(Name alias, Table<LessonsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Lessons(Name alias, Table<LessonsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public Lessons(String alias) {
        this(DSL.name(alias), LESSONS);
    }

    public Lessons(Name alias) {
        this(alias, LESSONS);
    }

    public Lessons() {
        this(DSL.name("lessons"), null);
    }

    public <O extends Record> Lessons(Table<O> child, ForeignKey<O, LessonsRecord> key) {
        super(child, key, LESSONS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<LessonsRecord, Integer> getIdentity() {
        return (Identity<LessonsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<LessonsRecord> getPrimaryKey() {
        return Keys.CLASSES_PKEY;
    }

    @Override
    public List<ForeignKey<LessonsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CLASSES__CLASSES_GROUPID_FKEY);
    }

    private transient Groups _groups;

    public Groups groups() {
        if (_groups == null)
            _groups = new Groups(this, Keys.CLASSES__CLASSES_GROUPID_FKEY);

        return _groups;
    }

    @Override
    public Lessons as(String alias) {
        return new Lessons(DSL.name(alias), this);
    }

    @Override
    public Lessons as(Name alias) {
        return new Lessons(alias, this);
    }

    @Override
    public Lessons as(Table<?> alias) {
        return new Lessons(alias.getQualifiedName(), this);
    }

    @Override
    public Lessons rename(String name) {
        return new Lessons(DSL.name(name), null);
    }

    @Override
    public Lessons rename(Name name) {
        return new Lessons(name, null);
    }

    @Override
    public Lessons rename(Table<?> name) {
        return new Lessons(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, String, LocalDate, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    public <U> SelectField<U> mapping(Function6<? super Integer, ? super Integer, ? super String, ? super LocalDate, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super Integer, ? super Integer, ? super String, ? super LocalDate, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
