/*
 * This file is generated by jOOQ.
 */
package edu.java.jooq.tables;


import edu.java.jooq.Keys;
import edu.java.jooq.Public;
import edu.java.jooq.tables.records.ClassesRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Classes extends TableImpl<ClassesRecord> {

    private static final long serialVersionUID = 1L;

    public static final Classes CLASSES = new Classes();

    @Override
    public Class<ClassesRecord> getRecordType() {
        return ClassesRecord.class;
    }

    public final TableField<ClassesRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    public final TableField<ClassesRecord, Long> GROUPID = createField(DSL.name("groupid"), SQLDataType.BIGINT, this, "");

    public final TableField<ClassesRecord, String> DISCIPLINE = createField(DSL.name("discipline"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    public final TableField<ClassesRecord, LocalDate> CLASSDATE = createField(DSL.name("classdate"), SQLDataType.LOCALDATE.nullable(false), this, "");

    public final TableField<ClassesRecord, String> CLASSTIME = createField(DSL.name("classtime"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    public final TableField<ClassesRecord, String> CLASSROOM = createField(DSL.name("classroom"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private Classes(Name alias, Table<ClassesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Classes(Name alias, Table<ClassesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public Classes(String alias) {
        this(DSL.name(alias), CLASSES);
    }

    public Classes(Name alias) {
        this(alias, CLASSES);
    }

    public Classes() {
        this(DSL.name("classes"), null);
    }

    public <O extends Record> Classes(Table<O> child, ForeignKey<O, ClassesRecord> key) {
        super(child, key, CLASSES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ClassesRecord, Integer> getIdentity() {
        return (Identity<ClassesRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ClassesRecord> getPrimaryKey() {
        return Keys.CLASSES_PKEY;
    }

    @Override
    public List<ForeignKey<ClassesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CLASSES__CLASSES_GROUPID_FKEY);
    }

    private transient Groups _groups;

    public Groups groups() {
        if (_groups == null)
            _groups = new Groups(this, Keys.CLASSES__CLASSES_GROUPID_FKEY);

        return _groups;
    }

    @Override
    public Classes as(String alias) {
        return new Classes(DSL.name(alias), this);
    }

    @Override
    public Classes as(Name alias) {
        return new Classes(alias, this);
    }

    @Override
    public Classes as(Table<?> alias) {
        return new Classes(alias.getQualifiedName(), this);
    }

    @Override
    public Classes rename(String name) {
        return new Classes(DSL.name(name), null);
    }

    @Override
    public Classes rename(Name name) {
        return new Classes(name, null);
    }

    @Override
    public Classes rename(Table<?> name) {
        return new Classes(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Long, String, LocalDate, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    public <U> SelectField<U> mapping(Function6<? super Integer, ? super Long, ? super String, ? super LocalDate, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super Integer, ? super Long, ? super String, ? super LocalDate, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
