spring:
  application:
    name: scrapper
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/schedule
    username: postgres
    password: postgres
  jackson:
    time-zone: Asia/Yekaterinburg


app:
  codes: 429, 503
  strategy: CONSTANT
  use-queue: false



logging:
  config: classpath:log4j2-plain.xml
