// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

// Protobuf Java Version: 3.25.1
package common;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_Lesson_descriptor;
  public static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_Lesson_fieldAccessorTable;
  public static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_LessonResponse_descriptor;
  public static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_LessonResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_ScheduleResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_ScheduleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_IdRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_IdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_BooleanResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_common_BooleanResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014common.proto\022\006common\"9\n\006Lesson\022\017\n\007subje" +
      "ct\030\001 \001(\t\022\014\n\004time\030\002 \001(\t\022\021\n\tclassroom\030\003 \001(" +
      "\t\"?\n\016LessonResponse\022\013\n\003day\030\001 \001(\t\022\037\n\007lesso" +
      "ns\030\002 \003(\0132\016.common.Lesson\";\n\020ScheduleRespo" +
      "nse\022\'\n\010schedule\030\001 \003(\0132\025.common.LessonResp" +
      "onse\"\027\n\tIdRequest\022\n\n\002id\030\001 \001(\003\" \n\017Boolean" +
      "Response\022\r\n\005value\030\001 \001(\010B\030\n\024edu.java.grpc" +
      ".commonP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_common_Lesson_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_common_Lesson_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_Lesson_descriptor,
        new String[] { "Subject", "Time", "Classroom", });
    internal_static_common_LessonResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_common_LessonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_LessonResponse_descriptor,
        new String[] { "Day", "Lessons", });
    internal_static_common_ScheduleResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_common_ScheduleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_ScheduleResponse_descriptor,
        new String[] { "Schedule", });
    internal_static_common_IdRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_common_IdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_IdRequest_descriptor,
        new String[] { "Id", });
    internal_static_common_BooleanResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_common_BooleanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_common_BooleanResponse_descriptor,
        new String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
