// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

// Protobuf Java Version: 3.25.1
package common;


import builder.response.LessonOrBuilder;
import builder.response.LessonResponseOrBuilder;

public final class LessonResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:common.LessonResponse)
    LessonResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LessonResponse.newBuilder() to construct.
  private LessonResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LessonResponse() {
    day_ = "";
    classes_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new LessonResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Common.internal_static_common_LessonResponse_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Common.internal_static_common_LessonResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            LessonResponse.class, LessonResponse.Builder.class);
  }

  public static final int DAY_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object day_ = "";

  @Override
  public String getDay() {
    Object ref = day_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      day_ = s;
      return s;
    }
  }

  @Override
  public com.google.protobuf.ByteString
      getDayBytes() {
    Object ref = day_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      day_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLASSES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<Lesson> classes_;

  @Override
  public java.util.List<Lesson> getClassesList() {
    return classes_;
  }

  @Override
  public java.util.List<? extends LessonOrBuilder>
      getClassesOrBuilderList() {
    return classes_;
  }

  @Override
  public int getClassesCount() {
    return classes_.size();
  }

  @Override
  public Lesson getClasses(int index) {
    return classes_.get(index);
  }

  @Override
  public LessonOrBuilder getClassesOrBuilder(
      int index) {
    return classes_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(day_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, day_);
    }
    for (int i = 0; i < classes_.size(); i++) {
      output.writeMessage(2, classes_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(day_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, day_);
    }
    for (int i = 0; i < classes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, classes_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof LessonResponse)) {
      return super.equals(obj);
    }
    LessonResponse other = (LessonResponse) obj;

    if (!getDay()
        .equals(other.getDay())) return false;
    if (!getClassesList()
        .equals(other.getClassesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DAY_FIELD_NUMBER;
    hash = (53 * hash) + getDay().hashCode();
    if (getClassesCount() > 0) {
      hash = (37 * hash) + CLASSES_FIELD_NUMBER;
      hash = (53 * hash) + getClassesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static LessonResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LessonResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LessonResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LessonResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LessonResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LessonResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LessonResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LessonResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static LessonResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static LessonResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static LessonResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LessonResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(LessonResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:common.LessonResponse)
      LessonResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Common.internal_static_common_LessonResponse_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Common.internal_static_common_LessonResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LessonResponse.class, LessonResponse.Builder.class);
    }

    // Construct using LessonResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      day_ = "";
      if (classesBuilder_ == null) {
        classes_ = java.util.Collections.emptyList();
      } else {
        classes_ = null;
        classesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Common.internal_static_common_LessonResponse_descriptor;
    }

    @Override
    public LessonResponse getDefaultInstanceForType() {
      return LessonResponse.getDefaultInstance();
    }

    @Override
    public LessonResponse build() {
      LessonResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public LessonResponse buildPartial() {
      LessonResponse result = new LessonResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(LessonResponse result) {
      if (classesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          classes_ = java.util.Collections.unmodifiableList(classes_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.classes_ = classes_;
      } else {
        result.classes_ = classesBuilder_.build();
      }
    }

    private void buildPartial0(LessonResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.day_ = day_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof LessonResponse) {
        return mergeFrom((LessonResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(LessonResponse other) {
      if (other == LessonResponse.getDefaultInstance()) return this;
      if (!other.getDay().isEmpty()) {
        day_ = other.day_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (classesBuilder_ == null) {
        if (!other.classes_.isEmpty()) {
          if (classes_.isEmpty()) {
            classes_ = other.classes_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureClassesIsMutable();
            classes_.addAll(other.classes_);
          }
          onChanged();
        }
      } else {
        if (!other.classes_.isEmpty()) {
          if (classesBuilder_.isEmpty()) {
            classesBuilder_.dispose();
            classesBuilder_ = null;
            classes_ = other.classes_;
            bitField0_ = (bitField0_ & ~0x00000002);
            classesBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getClassesFieldBuilder() : null;
          } else {
            classesBuilder_.addAllMessages(other.classes_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              day_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              Lesson m =
                  input.readMessage(
                      Lesson.parser(),
                      extensionRegistry);
              if (classesBuilder_ == null) {
                ensureClassesIsMutable();
                classes_.add(m);
              } else {
                classesBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object day_ = "";

    public String getDay() {
      Object ref = day_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        day_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    public com.google.protobuf.ByteString
        getDayBytes() {
      Object ref = day_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        day_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public Builder setDay(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      day_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    public Builder clearDay() {
      day_ = getDefaultInstance().getDay();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    public Builder setDayBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      day_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<Lesson> classes_ =
      java.util.Collections.emptyList();
    private void ensureClassesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        classes_ = new java.util.ArrayList<Lesson>(classes_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            Lesson, Lesson.Builder, LessonOrBuilder> classesBuilder_;


    public java.util.List<Lesson> getClassesList() {
      if (classesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(classes_);
      } else {
        return classesBuilder_.getMessageList();
      }
    }

    public int getClassesCount() {
      if (classesBuilder_ == null) {
        return classes_.size();
      } else {
        return classesBuilder_.getCount();
      }
    }

    public Lesson getClasses(int index) {
      if (classesBuilder_ == null) {
        return classes_.get(index);
      } else {
        return classesBuilder_.getMessage(index);
      }
    }

    public Builder setClasses(
        int index, Lesson value) {
      if (classesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureClassesIsMutable();
        classes_.set(index, value);
        onChanged();
      } else {
        classesBuilder_.setMessage(index, value);
      }
      return this;
    }

    public Builder setClasses(
        int index, Lesson.Builder builderForValue) {
      if (classesBuilder_ == null) {
        ensureClassesIsMutable();
        classes_.set(index, builderForValue.build());
        onChanged();
      } else {
        classesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }

    public Builder addClasses(Lesson value) {
      if (classesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureClassesIsMutable();
        classes_.add(value);
        onChanged();
      } else {
        classesBuilder_.addMessage(value);
      }
      return this;
    }

    public Builder addClasses(
        int index, Lesson value) {
      if (classesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureClassesIsMutable();
        classes_.add(index, value);
        onChanged();
      } else {
        classesBuilder_.addMessage(index, value);
      }
      return this;
    }

    public Builder addClasses(
        Lesson.Builder builderForValue) {
      if (classesBuilder_ == null) {
        ensureClassesIsMutable();
        classes_.add(builderForValue.build());
        onChanged();
      } else {
        classesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }

    public Builder addClasses(
        int index, Lesson.Builder builderForValue) {
      if (classesBuilder_ == null) {
        ensureClassesIsMutable();
        classes_.add(index, builderForValue.build());
        onChanged();
      } else {
        classesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }

    public Builder addAllClasses(
        Iterable<? extends Lesson> values) {
      if (classesBuilder_ == null) {
        ensureClassesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, classes_);
        onChanged();
      } else {
        classesBuilder_.addAllMessages(values);
      }
      return this;
    }

    public Builder clearClasses() {
      if (classesBuilder_ == null) {
        classes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        classesBuilder_.clear();
      }
      return this;
    }

    public Builder removeClasses(int index) {
      if (classesBuilder_ == null) {
        ensureClassesIsMutable();
        classes_.remove(index);
        onChanged();
      } else {
        classesBuilder_.remove(index);
      }
      return this;
    }

    public Lesson.Builder getClassesBuilder(
        int index) {
      return getClassesFieldBuilder().getBuilder(index);
    }

    public LessonOrBuilder getClassesOrBuilder(
        int index) {
      if (classesBuilder_ == null) {
        return classes_.get(index);  } else {
        return classesBuilder_.getMessageOrBuilder(index);
      }
    }

    public java.util.List<? extends LessonOrBuilder>
         getClassesOrBuilderList() {
      if (classesBuilder_ != null) {
        return classesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(classes_);
      }
    }

    public Lesson.Builder addClassesBuilder() {
      return getClassesFieldBuilder().addBuilder(
          Lesson.getDefaultInstance());
    }

    public Lesson.Builder addClassesBuilder(
        int index) {
      return getClassesFieldBuilder().addBuilder(
          index, Lesson.getDefaultInstance());
    }

    public java.util.List<Lesson.Builder>
         getClassesBuilderList() {
      return getClassesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            Lesson, Lesson.Builder, LessonOrBuilder>
        getClassesFieldBuilder() {
      if (classesBuilder_ == null) {
        classesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                Lesson, Lesson.Builder, LessonOrBuilder>(
                classes_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        classes_ = null;
      }
      return classesBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:common.LessonResponse)
  }

  // @@protoc_insertion_point(class_scope:common.LessonResponse)
  private static final LessonResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new LessonResponse();
  }

  public static LessonResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LessonResponse>
      PARSER = new com.google.protobuf.AbstractParser<LessonResponse>() {
    @Override
    public LessonResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LessonResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<LessonResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public LessonResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

