// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

// Protobuf Java Version: 3.25.1
package common;


import builder.response.LessonOrBuilder;

public final class Lesson extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:common.schedule.Class)
    LessonOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Class.newBuilder() to construct.
  private Lesson(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Lesson() {
    subject_ = "";
    time_ = "";
    classroom_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Lesson();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Common.internal_static_common_Lesson_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Common.internal_static_common_Lesson_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Lesson.class, Lesson.Builder.class);
  }

  public static final int SUBJECT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object subject_ = "";

  @Override
  public String getSubject() {
    Object ref = subject_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      subject_ = s;
      return s;
    }
  }

  @Override
  public com.google.protobuf.ByteString
      getSubjectBytes() {
    Object ref = subject_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      subject_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object time_ = "";

  @Override
  public String getTime() {
    Object ref = time_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      time_ = s;
      return s;
    }
  }

  @Override
  public com.google.protobuf.ByteString
      getTimeBytes() {
    Object ref = time_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      time_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLASSROOM_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile Object classroom_ = "";

  @Override
  public String getClassroom() {
    Object ref = classroom_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      classroom_ = s;
      return s;
    }
  }

  @Override
  public com.google.protobuf.ByteString
      getClassroomBytes() {
    Object ref = classroom_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      classroom_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(subject_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, subject_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(time_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, time_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(classroom_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, classroom_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(subject_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, subject_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(time_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, time_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(classroom_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, classroom_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Lesson)) {
      return super.equals(obj);
    }
    Lesson other = (Lesson) obj;

    if (!getSubject()
        .equals(other.getSubject())) return false;
    if (!getTime()
        .equals(other.getTime())) return false;
    if (!getClassroom()
        .equals(other.getClassroom())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUBJECT_FIELD_NUMBER;
    hash = (53 * hash) + getSubject().hashCode();
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + getTime().hashCode();
    hash = (37 * hash) + CLASSROOM_FIELD_NUMBER;
    hash = (53 * hash) + getClassroom().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Lesson parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Lesson parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Lesson parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Lesson parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Lesson parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Lesson parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Lesson parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Lesson parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Lesson parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static Lesson parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Lesson parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Lesson parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Lesson prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:common.schedule.Class)
      LessonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Common.internal_static_common_Lesson_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Common.internal_static_common_Lesson_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Lesson.class, Lesson.Builder.class);
    }

    // Construct using Lesson.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      subject_ = "";
      time_ = "";
      classroom_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Common.internal_static_common_Lesson_descriptor;
    }

    @Override
    public Lesson getDefaultInstanceForType() {
      return Lesson.getDefaultInstance();
    }

    @Override
    public Lesson build() {
      Lesson result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Lesson buildPartial() {
      Lesson result = new Lesson(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(Lesson result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.subject_ = subject_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.time_ = time_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.classroom_ = classroom_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Lesson) {
        return mergeFrom((Lesson)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Lesson other) {
      if (other == Lesson.getDefaultInstance()) return this;
      if (!other.getSubject().isEmpty()) {
        subject_ = other.subject_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getTime().isEmpty()) {
        time_ = other.time_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getClassroom().isEmpty()) {
        classroom_ = other.classroom_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              subject_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              time_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              classroom_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object subject_ = "";

    public String getSubject() {
      Object ref = subject_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        subject_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    public com.google.protobuf.ByteString
        getSubjectBytes() {
      Object ref = subject_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        subject_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public Builder setSubject(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      subject_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    public Builder clearSubject() {
      subject_ = getDefaultInstance().getSubject();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    public Builder setSubjectBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      subject_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private Object time_ = "";

    public String getTime() {
      Object ref = time_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        time_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    public com.google.protobuf.ByteString
        getTimeBytes() {
      Object ref = time_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public Builder setTime(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      time_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    public Builder clearTime() {
      time_ = getDefaultInstance().getTime();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    public Builder setTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      time_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private Object classroom_ = "";

    public String getClassroom() {
      Object ref = classroom_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        classroom_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    public com.google.protobuf.ByteString
        getClassroomBytes() {
      Object ref = classroom_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        classroom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public Builder setClassroom(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      classroom_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    public Builder clearClassroom() {
      classroom_ = getDefaultInstance().getClassroom();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    public Builder setClassroomBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      classroom_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:common.schedule.Class)
  }

  // @@protoc_insertion_point(class_scope:common.schedule.Class)
  private static final Lesson DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Lesson();
  }

  public static Lesson getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Lesson>
      PARSER = new com.google.protobuf.AbstractParser<Lesson>() {
    @Override
    public Lesson parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Lesson> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Lesson> getParserForType() {
    return PARSER;
  }

  @Override
  public Lesson getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

