// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

// Protobuf Java Version: 3.25.1
package common;


import builder.response.LessonResponseOrBuilder;
import builder.response.ScheduleResponseOrBuilder;

public final class ScheduleResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:common.ScheduleResponse)
    ScheduleResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ScheduleResponse.newBuilder() to construct.
  private ScheduleResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ScheduleResponse() {
    schedule_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ScheduleResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Common.internal_static_common_ScheduleResponse_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Common.internal_static_common_ScheduleResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ScheduleResponse.class, ScheduleResponse.Builder.class);
  }

  public static final int SCHEDULE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<LessonResponse> schedule_;

  @Override
  public java.util.List<LessonResponse> getScheduleList() {
    return schedule_;
  }

  @Override
  public java.util.List<? extends LessonResponseOrBuilder>
      getScheduleOrBuilderList() {
    return schedule_;
  }

  @Override
  public int getScheduleCount() {
    return schedule_.size();
  }

  @Override
  public LessonResponse getSchedule(int index) {
    return schedule_.get(index);
  }

  @Override
  public LessonResponseOrBuilder getScheduleOrBuilder(
      int index) {
    return schedule_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < schedule_.size(); i++) {
      output.writeMessage(1, schedule_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < schedule_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, schedule_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ScheduleResponse)) {
      return super.equals(obj);
    }
    ScheduleResponse other = (ScheduleResponse) obj;

    if (!getScheduleList()
        .equals(other.getScheduleList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getScheduleCount() > 0) {
      hash = (37 * hash) + SCHEDULE_FIELD_NUMBER;
      hash = (53 * hash) + getScheduleList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ScheduleResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ScheduleResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ScheduleResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ScheduleResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ScheduleResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ScheduleResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ScheduleResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ScheduleResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ScheduleResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ScheduleResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ScheduleResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ScheduleResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ScheduleResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:common.ScheduleResponse)
          ScheduleResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Common.internal_static_common_ScheduleResponse_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Common.internal_static_common_ScheduleResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ScheduleResponse.class, ScheduleResponse.Builder.class);
    }

    // Construct using ScheduleResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (scheduleBuilder_ == null) {
        schedule_ = java.util.Collections.emptyList();
      } else {
        schedule_ = null;
        scheduleBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Common.internal_static_common_ScheduleResponse_descriptor;
    }

    @Override
    public ScheduleResponse getDefaultInstanceForType() {
      return ScheduleResponse.getDefaultInstance();
    }

    @Override
    public ScheduleResponse build() {
      ScheduleResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ScheduleResponse buildPartial() {
      ScheduleResponse result = new ScheduleResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(ScheduleResponse result) {
      if (scheduleBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          schedule_ = java.util.Collections.unmodifiableList(schedule_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.schedule_ = schedule_;
      } else {
        result.schedule_ = scheduleBuilder_.build();
      }
    }

    private void buildPartial0(ScheduleResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ScheduleResponse) {
        return mergeFrom((ScheduleResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ScheduleResponse other) {
      if (other == ScheduleResponse.getDefaultInstance()) return this;
      if (scheduleBuilder_ == null) {
        if (!other.schedule_.isEmpty()) {
          if (schedule_.isEmpty()) {
            schedule_ = other.schedule_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureScheduleIsMutable();
            schedule_.addAll(other.schedule_);
          }
          onChanged();
        }
      } else {
        if (!other.schedule_.isEmpty()) {
          if (scheduleBuilder_.isEmpty()) {
            scheduleBuilder_.dispose();
            scheduleBuilder_ = null;
            schedule_ = other.schedule_;
            bitField0_ = (bitField0_ & ~0x00000001);
            scheduleBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getScheduleFieldBuilder() : null;
          } else {
            scheduleBuilder_.addAllMessages(other.schedule_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              LessonResponse m =
                  input.readMessage(
                      LessonResponse.parser(),
                      extensionRegistry);
              if (scheduleBuilder_ == null) {
                ensureScheduleIsMutable();
                schedule_.add(m);
              } else {
                scheduleBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<LessonResponse> schedule_ =
      java.util.Collections.emptyList();
    private void ensureScheduleIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        schedule_ = new java.util.ArrayList<LessonResponse>(schedule_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        LessonResponse, LessonResponse.Builder, LessonResponseOrBuilder> scheduleBuilder_;


    public java.util.List<LessonResponse> getScheduleList() {
      if (scheduleBuilder_ == null) {
        return java.util.Collections.unmodifiableList(schedule_);
      } else {
        return scheduleBuilder_.getMessageList();
      }
    }

    public int getScheduleCount() {
      if (scheduleBuilder_ == null) {
        return schedule_.size();
      } else {
        return scheduleBuilder_.getCount();
      }
    }

    public LessonResponse getSchedule(int index) {
      if (scheduleBuilder_ == null) {
        return schedule_.get(index);
      } else {
        return scheduleBuilder_.getMessage(index);
      }
    }

    public Builder setSchedule(
        int index, LessonResponse value) {
      if (scheduleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureScheduleIsMutable();
        schedule_.set(index, value);
        onChanged();
      } else {
        scheduleBuilder_.setMessage(index, value);
      }
      return this;
    }

    public Builder setSchedule(
        int index, LessonResponse.Builder builderForValue) {
      if (scheduleBuilder_ == null) {
        ensureScheduleIsMutable();
        schedule_.set(index, builderForValue.build());
        onChanged();
      } else {
        scheduleBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }

    public Builder addSchedule(LessonResponse value) {
      if (scheduleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureScheduleIsMutable();
        schedule_.add(value);
        onChanged();
      } else {
        scheduleBuilder_.addMessage(value);
      }
      return this;
    }

    public Builder addSchedule(
        int index, LessonResponse value) {
      if (scheduleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureScheduleIsMutable();
        schedule_.add(index, value);
        onChanged();
      } else {
        scheduleBuilder_.addMessage(index, value);
      }
      return this;
    }

    public Builder addSchedule(
        LessonResponse.Builder builderForValue) {
      if (scheduleBuilder_ == null) {
        ensureScheduleIsMutable();
        schedule_.add(builderForValue.build());
        onChanged();
      } else {
        scheduleBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }

    public Builder addSchedule(
        int index, LessonResponse.Builder builderForValue) {
      if (scheduleBuilder_ == null) {
        ensureScheduleIsMutable();
        schedule_.add(index, builderForValue.build());
        onChanged();
      } else {
        scheduleBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }

    public Builder addAllSchedule(
        Iterable<? extends LessonResponse> values) {
      if (scheduleBuilder_ == null) {
        ensureScheduleIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, schedule_);
        onChanged();
      } else {
        scheduleBuilder_.addAllMessages(values);
      }
      return this;
    }

    public Builder clearSchedule() {
      if (scheduleBuilder_ == null) {
        schedule_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        scheduleBuilder_.clear();
      }
      return this;
    }

    public Builder removeSchedule(int index) {
      if (scheduleBuilder_ == null) {
        ensureScheduleIsMutable();
        schedule_.remove(index);
        onChanged();
      } else {
        scheduleBuilder_.remove(index);
      }
      return this;
    }

    public LessonResponse.Builder getScheduleBuilder(
        int index) {
      return getScheduleFieldBuilder().getBuilder(index);
    }

    public LessonResponseOrBuilder getScheduleOrBuilder(
        int index) {
      if (scheduleBuilder_ == null) {
        return schedule_.get(index);  } else {
        return scheduleBuilder_.getMessageOrBuilder(index);
      }
    }

    public java.util.List<? extends LessonResponseOrBuilder>
         getScheduleOrBuilderList() {
      if (scheduleBuilder_ != null) {
        return scheduleBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(schedule_);
      }
    }

    public LessonResponse.Builder addScheduleBuilder() {
      return getScheduleFieldBuilder().addBuilder(
          LessonResponse.getDefaultInstance());
    }

    public LessonResponse.Builder addScheduleBuilder(
        int index) {
      return getScheduleFieldBuilder().addBuilder(
          index, LessonResponse.getDefaultInstance());
    }

    public java.util.List<LessonResponse.Builder>
         getScheduleBuilderList() {
      return getScheduleFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        LessonResponse, LessonResponse.Builder, LessonResponseOrBuilder>
        getScheduleFieldBuilder() {
      if (scheduleBuilder_ == null) {
        scheduleBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            LessonResponse, LessonResponse.Builder, LessonResponseOrBuilder>(
                schedule_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        schedule_ = null;
      }
      return scheduleBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:common.ScheduleResponse)
  }

  // @@protoc_insertion_point(class_scope:common.ScheduleResponse)
  private static final ScheduleResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ScheduleResponse();
  }

  public static ScheduleResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ScheduleResponse>
      PARSER = new com.google.protobuf.AbstractParser<ScheduleResponse>() {
    @Override
    public ScheduleResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ScheduleResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ScheduleResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public ScheduleResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

