/*
 * This file is generated by jOOQ.
 */
package edu.java.jooq;


import edu.java.jooq.tables.Classes;
import edu.java.jooq.tables.Databasechangelog;
import edu.java.jooq.tables.Databasechangeloglock;
import edu.java.jooq.tables.Groups;
import edu.java.jooq.tables.Student;


@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    public static final Classes CLASSES = Classes.CLASSES;

    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    public static final Groups GROUPS = Groups.GROUPS;

    public static final Student STUDENT = Student.STUDENT;
}
