// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/schedule_service.proto

// Protobuf Java Version: 3.25.1
package schedule;

public interface GetScheduleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:schedule.GetScheduleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string time = 2;</code>
   * @return The time.
   */
  String getTime();
  /**
   * <code>string time = 2;</code>
   * @return The bytes for time.
   */
  com.google.protobuf.ByteString
      getTimeBytes();
}
