// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/schedule_service.proto

// Protobuf Java Version: 3.25.1
package builder.request;

public interface GetScheduleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetScheduleRequest)
    com.google.protobuf.MessageOrBuilder {


  long getId();


  String getTime();

  com.google.protobuf.ByteString
      getTimeBytes();
}
