// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

// Protobuf Java Version: 3.25.1
package builder.request;

public interface IdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.IdRequest)
    com.google.protobuf.MessageOrBuilder {


  long getId();
}
