// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/notification_service.proto

// Protobuf Java Version: 3.25.1
package builder.request;

public interface UpdateGroupRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notification.UpdateGroupRequest)
    com.google.protobuf.MessageOrBuilder {

    long getId();

    String getGroup();
    com.google.protobuf.ByteString
      getGroupBytes();
}
