/*
 * This file is generated by jOOQ.
 */
package edu.java.jooq.tables;


import edu.java.jooq.Keys;
import edu.java.jooq.Public;
import edu.java.jooq.tables.records.GroupsRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Groups extends TableImpl<GroupsRecord> {

    private static final long serialVersionUID = 1L;

    public static final Groups GROUPS = new Groups();

    @Override
    public Class<GroupsRecord> getRecordType() {
        return GroupsRecord.class;
    }

    public final TableField<GroupsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    public final TableField<GroupsRecord, String> GROUPNAME = createField(DSL.name("groupname"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private Groups(Name alias, Table<GroupsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Groups(Name alias, Table<GroupsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public Groups(String alias) {
        this(DSL.name(alias), GROUPS);
    }

    public Groups(Name alias) {
        this(alias, GROUPS);
    }

    public Groups() {
        this(DSL.name("groups"), null);
    }

    public <O extends Record> Groups(Table<O> child, ForeignKey<O, GroupsRecord> key) {
        super(child, key, GROUPS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<GroupsRecord, Integer> getIdentity() {
        return (Identity<GroupsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<GroupsRecord> getPrimaryKey() {
        return Keys.GROUPS_PKEY;
    }

    @Override
    public Groups as(String alias) {
        return new Groups(DSL.name(alias), this);
    }

    @Override
    public Groups as(Name alias) {
        return new Groups(alias, this);
    }

    @Override
    public Groups as(Table<?> alias) {
        return new Groups(alias.getQualifiedName(), this);
    }

    @Override
    public Groups rename(String name) {
        return new Groups(DSL.name(name), null);
    }

    @Override
    public Groups rename(Name name) {
        return new Groups(name, null);
    }

    @Override
    public Groups rename(Table<?> name) {
        return new Groups(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    public <U> SelectField<U> mapping(Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
