/*
 * This file is generated by jOOQ.
 */
package edu.java.jooq.tables;


import edu.java.jooq.Keys;
import edu.java.jooq.Public;
import edu.java.jooq.tables.records.StudentRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Student extends TableImpl<StudentRecord> {

    private static final long serialVersionUID = 1L;

    public static final Student STUDENT = new Student();

    @Override
    public Class<StudentRecord> getRecordType() {
        return StudentRecord.class;
    }

    public final TableField<StudentRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    public final TableField<StudentRecord, Integer> GROUPID = createField(DSL.name("groupid"), SQLDataType.INTEGER, this, "");

    public final TableField<StudentRecord, Boolean> ISNOTIFIED = createField(DSL.name("isnotified"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    public final TableField<StudentRecord, Integer> MAILINGTIME = createField(DSL.name("mailingtime"), SQLDataType.INTEGER, this, "");

    private Student(Name alias, Table<StudentRecord> aliased) {
        this(alias, aliased, null);
    }

    private Student(Name alias, Table<StudentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public Student(String alias) {
        this(DSL.name(alias), STUDENT);
    }

    public Student(Name alias) {
        this(alias, STUDENT);
    }

    public Student() {
        this(DSL.name("student"), null);
    }

    public <O extends Record> Student(Table<O> child, ForeignKey<O, StudentRecord> key) {
        super(child, key, STUDENT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<StudentRecord, Long> getIdentity() {
        return (Identity<StudentRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<StudentRecord> getPrimaryKey() {
        return Keys.STUDENT_PKEY;
    }

    @Override
    public List<ForeignKey<StudentRecord, ?>> getReferences() {
        return Arrays.asList(Keys.STUDENT__STUDENT_GROUPID_FKEY);
    }

    private transient Groups _groups;

    public Groups groups() {
        if (_groups == null)
            _groups = new Groups(this, Keys.STUDENT__STUDENT_GROUPID_FKEY);

        return _groups;
    }

    @Override
    public Student as(String alias) {
        return new Student(DSL.name(alias), this);
    }

    @Override
    public Student as(Name alias) {
        return new Student(alias, this);
    }

    @Override
    public Student as(Table<?> alias) {
        return new Student(alias.getQualifiedName(), this);
    }

    @Override
    public Student rename(String name) {
        return new Student(DSL.name(name), null);
    }

    @Override
    public Student rename(Name name) {
        return new Student(name, null);
    }

    @Override
    public Student rename(Table<?> name) {
        return new Student(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Integer, Boolean, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    public <U> SelectField<U> mapping(Function4<? super Long, ? super Integer, ? super Boolean, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super Long, ? super Integer, ? super Boolean, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
