/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.Classes;
import jooq.tables.Databasechangeloglock;
import jooq.tables.Groups;
import jooq.tables.Student;
import jooq.tables.records.ClassesRecord;
import jooq.tables.records.DatabasechangeloglockRecord;
import jooq.tables.records.GroupsRecord;
import jooq.tables.records.StudentRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ClassesRecord> CLASSES_PKEY = Internal.createUniqueKey(Classes.CLASSES, DSL.name("classes_pkey"), new TableField[] { Classes.CLASSES.ID }, true);
    public static final UniqueKey<DatabasechangeloglockRecord> DATABASECHANGELOGLOCK_PKEY = Internal.createUniqueKey(Databasechangeloglock.DATABASECHANGELOGLOCK, DSL.name("databasechangeloglock_pkey"), new TableField[] { Databasechangeloglock.DATABASECHANGELOGLOCK.ID }, true);
    public static final UniqueKey<GroupsRecord> GROUPS_PKEY = Internal.createUniqueKey(Groups.GROUPS, DSL.name("groups_pkey"), new TableField[] { Groups.GROUPS.ID }, true);
    public static final UniqueKey<StudentRecord> STUDENT_PKEY = Internal.createUniqueKey(Student.STUDENT, DSL.name("student_pkey"), new TableField[] { Student.STUDENT.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ClassesRecord, GroupsRecord> CLASSES__CLASSES_GROUPID_FKEY = Internal.createForeignKey(Classes.CLASSES, DSL.name("classes_groupid_fkey"), new TableField[] { Classes.CLASSES.GROUPID }, Keys.GROUPS_PKEY, new TableField[] { Groups.GROUPS.ID }, true);
    public static final ForeignKey<StudentRecord, GroupsRecord> STUDENT__STUDENT_GROUPID_FKEY = Internal.createForeignKey(Student.STUDENT, DSL.name("student_groupid_fkey"), new TableField[] { Student.STUDENT.GROUPID }, Keys.GROUPS_PKEY, new TableField[] { Groups.GROUPS.ID }, true);
}
