/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.Lessons;
import jooq.tables.Databasechangelog;
import jooq.tables.Databasechangeloglock;
import jooq.tables.Groups;
import jooq.tables.Student;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    public static final Public PUBLIC = new Public();

    public final Lessons LESSONS = Lessons.LESSONS;

    public final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    public final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    public final Groups GROUPS = Groups.GROUPS;

    public final Student STUDENT = Student.STUDENT;

    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Lessons.LESSONS,
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            Groups.GROUPS,
            Student.STUDENT
        );
    }
}
