/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.Lessons;
import jooq.tables.Databasechangelog;
import jooq.tables.Databasechangeloglock;
import jooq.tables.Groups;
import jooq.tables.Student;

@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    public static final Lessons LESSONS = Lessons.LESSONS;

    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    public static final Groups GROUPS = Groups.GROUPS;

    public static final Student STUDENT = Student.STUDENT;
}
