// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

// Protobuf Java Version: 3.25.1
package builder.response;

public interface BooleanResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.BooleanResponse)
    com.google.protobuf.MessageOrBuilder {


  boolean getValue();
}
