// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

// Protobuf Java Version: 3.25.1
package builder.response;

public interface LessonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.schedule.Class)
    com.google.protobuf.MessageOrBuilder {


  String getSubject();

  com.google.protobuf.ByteString
      getSubjectBytes();


  String getTime();

  com.google.protobuf.ByteString
      getTimeBytes();


  String getClassroom();

  com.google.protobuf.ByteString
      getClassroomBytes();
}
