// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

// Protobuf Java Version: 3.25.1
package builder.response;

import common.Lesson;

public interface LessonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.LessonResponse)
    com.google.protobuf.MessageOrBuilder {


  String getDay();

  com.google.protobuf.ByteString
      getDayBytes();


  java.util.List<Lesson>
      getClassesList();

  Lesson getClasses(int index);

  int getClassesCount();

  java.util.List<? extends LessonOrBuilder>
      getClassesOrBuilderList();

  LessonOrBuilder getClassesOrBuilder(
      int index);
}
