// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

// Protobuf Java Version: 3.25.1
package builder.response;

import common.LessonResponse;

public interface ScheduleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.ScheduleResponse)
    com.google.protobuf.MessageOrBuilder {


  java.util.List<LessonResponse>
      getScheduleList();

  LessonResponse getSchedule(int index);

  int getScheduleCount();

  java.util.List<? extends LessonResponseOrBuilder>
      getScheduleOrBuilderList();

  LessonResponseOrBuilder getScheduleOrBuilder(
      int index);
}
