/*
 * This file is generated by jOOQ.
 */
package edu.java.jooq.tables.records;


import edu.java.jooq.tables.Groups;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GroupsRecord extends UpdatableRecordImpl<GroupsRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    public void setId(Integer value) {
        set(0, value);
    }

    public Integer getId() {
        return (Integer) get(0);
    }

    public void setGroupname(String value) {
        set(1, value);
    }

    public String getGroupname() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Groups.GROUPS.ID;
    }

    @Override
    public Field<String> field2() {
        return Groups.GROUPS.GROUPNAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getGroupname();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getGroupname();
    }

    @Override
    public GroupsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GroupsRecord value2(String value) {
        setGroupname(value);
        return this;
    }

    @Override
    public GroupsRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public GroupsRecord() {
        super(Groups.GROUPS);
    }

    public GroupsRecord(Integer id, String groupname) {
        super(Groups.GROUPS);

        setId(id);
        setGroupname(groupname);
        resetChangedOnNotNull();
    }
}
