/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jooq.tables.Classes;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClassesRecord extends UpdatableRecordImpl<ClassesRecord> implements Record6<Integer, Integer, String, LocalDate, String, String> {

    private static final long serialVersionUID = 1L;

    public void setId(Integer value) {
        set(0, value);
    }

    public Integer getId() {
        return (Integer) get(0);
    }

    public void setGroupid(Integer value) {
        set(1, value);
    }

    public Integer getGroupid() {
        return (Integer) get(1);
    }

    public void setDiscipline(String value) {
        set(2, value);
    }

    public String getDiscipline() {
        return (String) get(2);
    }

    public void setClassdate(LocalDate value) {
        set(3, value);
    }

    public LocalDate getClassdate() {
        return (LocalDate) get(3);
    }

    public void setClasstime(String value) {
        set(4, value);
    }

    public String getClasstime() {
        return (String) get(4);
    }

    public void setClassroom(String value) {
        set(5, value);
    }

    public String getClassroom() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, String, LocalDate, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, String, LocalDate, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Classes.CLASSES.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Classes.CLASSES.GROUPID;
    }

    @Override
    public Field<String> field3() {
        return Classes.CLASSES.DISCIPLINE;
    }

    @Override
    public Field<LocalDate> field4() {
        return Classes.CLASSES.CLASSDATE;
    }

    @Override
    public Field<String> field5() {
        return Classes.CLASSES.CLASSTIME;
    }

    @Override
    public Field<String> field6() {
        return Classes.CLASSES.CLASSROOM;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getGroupid();
    }

    @Override
    public String component3() {
        return getDiscipline();
    }

    @Override
    public LocalDate component4() {
        return getClassdate();
    }

    @Override
    public String component5() {
        return getClasstime();
    }

    @Override
    public String component6() {
        return getClassroom();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getGroupid();
    }

    @Override
    public String value3() {
        return getDiscipline();
    }

    @Override
    public LocalDate value4() {
        return getClassdate();
    }

    @Override
    public String value5() {
        return getClasstime();
    }

    @Override
    public String value6() {
        return getClassroom();
    }

    @Override
    public ClassesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ClassesRecord value2(Integer value) {
        setGroupid(value);
        return this;
    }

    @Override
    public ClassesRecord value3(String value) {
        setDiscipline(value);
        return this;
    }

    @Override
    public ClassesRecord value4(LocalDate value) {
        setClassdate(value);
        return this;
    }

    @Override
    public ClassesRecord value5(String value) {
        setClasstime(value);
        return this;
    }

    @Override
    public ClassesRecord value6(String value) {
        setClassroom(value);
        return this;
    }

    @Override
    public ClassesRecord values(Integer value1, Integer value2, String value3, LocalDate value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public ClassesRecord() {
        super(Classes.CLASSES);
    }

    public ClassesRecord(Integer id, Integer groupid, String discipline, LocalDate classdate, String classtime, String classroom) {
        super(Classes.CLASSES);

        setId(id);
        setGroupid(groupid);
        setDiscipline(discipline);
        setClassdate(classdate);
        setClasstime(classtime);
        setClassroom(classroom);
        resetChangedOnNotNull();
    }
}
