/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jooq.tables.Student;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StudentRecord extends UpdatableRecordImpl<StudentRecord> implements Record4<Long, Integer, Boolean, Integer> {

    private static final long serialVersionUID = 1L;

    public void setId(Long value) {
        set(0, value);
    }

    public Long getId() {
        return (Long) get(0);
    }

    public void setGroupid(Integer value) {
        set(1, value);
    }

    public Integer getGroupid() {
        return (Integer) get(1);
    }

    public void setIsnotified(Boolean value) {
        set(2, value);
    }

    public Boolean getIsnotified() {
        return (Boolean) get(2);
    }

    public void setMailingtime(Integer value) {
        set(3, value);
    }

    public Integer getMailingtime() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Integer, Boolean, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Integer, Boolean, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Student.STUDENT.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Student.STUDENT.GROUPID;
    }

    @Override
    public Field<Boolean> field3() {
        return Student.STUDENT.ISNOTIFIED;
    }

    @Override
    public Field<Integer> field4() {
        return Student.STUDENT.MAILINGTIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getGroupid();
    }

    @Override
    public Boolean component3() {
        return getIsnotified();
    }

    @Override
    public Integer component4() {
        return getMailingtime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getGroupid();
    }

    @Override
    public Boolean value3() {
        return getIsnotified();
    }

    @Override
    public Integer value4() {
        return getMailingtime();
    }

    @Override
    public StudentRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public StudentRecord value2(Integer value) {
        setGroupid(value);
        return this;
    }

    @Override
    public StudentRecord value3(Boolean value) {
        setIsnotified(value);
        return this;
    }

    @Override
    public StudentRecord value4(Integer value) {
        setMailingtime(value);
        return this;
    }

    @Override
    public StudentRecord values(Long value1, Integer value2, Boolean value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public StudentRecord() {
        super(Student.STUDENT);
    }

    public StudentRecord(Long id, Integer groupid, Boolean isnotified, Integer mailingtime) {
        super(Student.STUDENT);

        setId(id);
        setGroupid(groupid);
        setIsnotified(isnotified);
        setMailingtime(mailingtime);
        resetChangedOnNotNull();
    }
}
